name: 'Setup Terraform Environment'
description: 'Setup Terraform with caching and AWS credentials'

inputs:
  terraform_version:
    description: 'Terraform version to install'
    required: false
    default: '1.7.0'
  aws_role:
    description: 'AWS IAM role ARN to assume'
    required: true
  aws_region:
    description: 'AWS region'
    required: false
    default: 'us-east-1'
  working_directory:
    description: 'Working directory for Terraform'
    required: false
    default: '.'

outputs:
  terraform_version:
    description: 'Installed Terraform version'
    value: ${{ steps.setup.outputs.terraform_version }}

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws_role }}
        aws-region: ${{ inputs.aws_region }}
        role-session-name: GitHubActions-Terraform

    - name: Setup Terraform
      id: setup
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Cache Terraform plugins
      uses: actions/cache@v4
      with:
        path: |
          ${{ inputs.working_directory }}/.terraform
          ~/.terraform.d/plugin-cache
        key: ${{ runner.os }}-terraform-${{ hashFiles(format('{0}/.terraform.lock.hcl', inputs.working_directory)) }}
        restore-keys: |
          ${{ runner.os }}-terraform-

    - name: Create plugin cache directory
      shell: bash
      run: |
        mkdir -p ~/.terraform.d/plugin-cache
        echo 'plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"' > ~/.terraformrc
